---
- name: Install default Apache     # description
  hosts: all                       # for all hosts
  become: yes                      # from sudo
  
  vars:                            # variables
    source_file: ./MyWebSite/path
    destin_file: /var/www/html
    owner      : Sofiia
  
  tasks:
  
  - name : Print text
    debug: 
      var: source_file              # print variable 
      
  - name: Install Apache
    yum:  name=httpd state=latest   # yum command
    
  - name: Copy home page
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache                                      
   
  - name: Start Apache
    service: name=httpd state=started enabled=yes
    
  handlers:
  - name: Restart Apavhe
    service: name=httpd state=restarted
    
    
