---
- name: Install default Apache
  hosts: all
  become: yes
  
  vars:
    source_file: ./MyWebSite/path
    destin_file: /var/www/html
  
  tasks:
  - name: Install Apache
    yum:  name=httpd state=latest
    
  - name: Copy home page
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache                                      
   
  - name: Start Apache
    service: name=httpd state=started enabled=yes
    
  handlers:
  - name: Restart Apavhe
    service: name=httpd state=restarted
    
    
